name: gnuchess 
version: 2.2
summary: Plays a game of chess. Run "gnuchess.readme" for more information.
description: |
     Gnuchess is an updated version of the GNU chess playing program. It is now
     based on the fruit chess engine and uses the UCI chess engine protocol. It has
     a simple alpha-numeric board display, and is also compatible with frontends
     like xboard, scid and eboard.
     This snap package also includes the xboard graphical frontend, which can be
     used either to play with gnuchess as an engine, or over the internet on any
     ICS-compatible service.
     Run "gnuchess" for the CLI engine, "gnuchess.xboard" for the GUI frontend,
     and "gnuchess.readme" for more information.
confinement: strict

apps:
  gnuchess:
    command: bin/gnuchess-script
    plugs: [home]  # needed to write log files in $HOME
  xboard:
    command: bin/xboard-script
    plugs: [x11, unity7, network, home]  # Needed to write game files in $HOME
  readme:
    command: bin/readme-script

parts:
    xboard:
        plugin: autotools
        source: xboard.tar.gz
        build-packages:
                - build-essential
                - g++
                - texinfo
                - libcairo2-dev
                - libcairo2
                - libgdk-pixbuf2.0-0
                - libglib2.0-0
                - libpango-1.0-0
                - librsvg2-2
                - libpangocairo-1.0-0
                - libpango1.0-dev
                - librsvg2-dev
                - libgtk2.0-0
                - libgtk2.0-dev
        stage-packages:
                - libcairo2
                - libgdk-pixbuf2.0-0
                - libglib2.0-0
                - libpango-1.0-0
                - librsvg2-2
                - libpangocairo-1.0-0
                - libgtk2.0-0
    gnuchess:
        plugin: autotools
        source: gnuchess.tar.gz
        build-packages:
                - build-essential
                - g++
        stage:
            - -share/gnuchess/gnuchess.ini
            - -share/info/dir
    glue:
        plugin: copy
        files:
             gnuchess-script: bin/gnuchess-script
             gnuchess-snap.ini: share/gnuchess/gnuchess.ini
             xboard-script: bin/xboard-script
             readme-script: bin/readme-script
    books:
        plugin: copy
        files:
             book.bin: share/gnuchess/book.bin
