name: gnuchess 
version: 1.0
summary: Plays a game of chess, either against the user or against itself 
description: |
     Gnuchess is an updated version of the GNU chess playing program. It is now
     based on the fruit chess engine and uses the UCI chess engine protocol. It has
     a simple alpha-numeric board display, and is also compatible with frontends
     like xboard, scid and eboard.
confinement: strict

apps:
  gnuchess:
    command: bin/gnuchess-script
    plugs: [home]

parts:
    gnuchess:
        plugin: autotools
        source: gnuchess.tar.gz
        stage:
            - -share/gnuchess/gnuchess.ini
    glue:
        plugin: copy
        files:
             gnuchess-script: bin/gnuchess-script
             gnuchess-snap.ini: share/gnuchess/gnuchess.ini
    books:
        plugin: copy
        files:
             book.bin: share/gnuchess/book.bin
