name: gnuchess 
version: 2.0
summary: Plays a game of chess, either against the user or against itself 
description: |
     Gnuchess is an updated version of the GNU chess playing program. It is now
     based on the fruit chess engine and uses the UCI chess engine protocol. It has
     a simple alpha-numeric board display, and is also compatible with frontends
     like xboard, scid and eboard.
confinement: strict

apps:
  gnuchess:
    command: bin/gnuchess-script
  xboard:
    command: bin/xboard-script
    plugs: [x11, unity7, network]

parts:
    xboard:
        plugin: autotools
        source: xboard.tar.gz
        build-packages:
                - texinfo
                - libcairo2-dev
                - libcairo2
                - libgdk-pixbuf2.0-0
                - libglib2.0-0
                - libpango-1.0-0
                - librsvg2-2
                - libpangocairo-1.0-0
                - libpango1.0-dev
                - librsvg2-dev
                - libgtk2.0-0
                - libgtk2.0-dev
        stage-packages:
                - libcairo2
                - libgdk-pixbuf2.0-0
                - libglib2.0-0
                - libpango-1.0-0
                - librsvg2-2
                - libpangocairo-1.0-0
                - libgtk2.0-0
    gnuchess:
        plugin: autotools
        source: gnuchess.tar.gz
        stage:
            - -share/gnuchess/gnuchess.ini
            - -share/info/dir
    glue:
        plugin: copy
        files:
             gnuchess-script: bin/gnuchess-script
             gnuchess-snap.ini: share/gnuchess/gnuchess.ini
             xboard-script: bin/xboard-script
    books:
        plugin: copy
        files:
             book.bin: share/gnuchess/book.bin
